# Generated by Django 4.2.10 on 2024-03-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_message_latitude_message_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
    ]
